# Generated by Django 4.0.4 on 2022-05-12 14:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("brand_name", models.CharField(blank=True, max_length=200)),
                (
                    "upc_ean_code",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("selling_price", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product_details",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "technical_details",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "about_product",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
